### ISSUE TITLE
Feature suggestion: repo collection folders

### ISSUE THREAD

**Issue by reinago** [sgrottel/checkouts-overview#16]
I guess many people keep check-outs organized in few folders, like a "source" one, a "websites" one, a "papers" one etc. If you could register these folders with the tool, finding the regular repos would be much quicker than scanning the whole machine. Maybe you also have weird/read-only checkouts somewhere that you do not want the tool to show to make it less messy.

**Comment by sgrottel** [comment]
I am not sure I fully understand the feature suggestion... What I understand, this is a suggestion to add settings to the scan dialog, default search folders, exclude folders, ... maybe a second button to quickly scan this preconfiguration.

Right?

Please clarify.
